// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Immutable audit trail for security, compliance, and forensic analysis
type AuditLog struct {
	ID uuid.UUID `json:"id"`
	// Specific event identifier (e.g., user.login, kyc.approved)
	EventType string `json:"event_type"`
	// High-level categorization for filtering and reporting
	EventCategory string `json:"event_category"`
	// Event severity for alerting and monitoring
	Severity        string      `json:"severity"`
	UserID          pgtype.UUID `json:"user_id"`
	ActorType       string      `json:"actor_type"`
	ActorIdentifier *string     `json:"actor_identifier"`
	Action          string      `json:"action"`
	ResourceType    *string     `json:"resource_type"`
	ResourceID      *string     `json:"resource_id"`
	IpAddress       *netip.Addr `json:"ip_address"`
	UserAgent       *string     `json:"user_agent"`
	RequestID       *string     `json:"request_id"`
	SessionID       *string     `json:"session_id"`
	// Flexible JSONB field for event-specific structured data
	Metadata      []byte  `json:"metadata"`
	PreviousState []byte  `json:"previous_state"`
	NewState      []byte  `json:"new_state"`
	Status        string  `json:"status"`
	FailureReason *string `json:"failure_reason"`
	// Auto-deletion timestamp for compliance with data retention policies
	RetentionUntil pgtype.Timestamptz `json:"retention_until"`
	IsSensitive    *bool              `json:"is_sensitive"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Stores JWT refresh tokens for user authentication
type RefreshToken struct {
	// Unique refresh token string (hashed)
	Token string `json:"token"`
	// Reference to user who owns this token
	UserID uuid.UUID `json:"user_id"`
	// Token expiration timestamp
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Timestamp when token was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when token was revoked (NULL if active)
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// IP address where token was created (audit trail)
	IpAddress *string `json:"ip_address"`
	// User agent where token was created (audit trail)
	UserAgent *string `json:"user_agent"`
}

// Stores user authentication and profile information
type User struct {
	// Unique user identifier (UUID v4)
	ID uuid.UUID `json:"id"`
	// User email address (unique, used for login)
	Email string `json:"email"`
	// Argon2id hashed password
	HashedPassword string `json:"hashed_password"`
	// KYC verification status: pending, verified, or rejected
	KycStatus string `json:"kyc_status"`
	// Timestamp when user was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when user was last updated (auto-updated)
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft delete timestamp (NULL if not deleted)
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	// User role for authorization: user (default) or admin
	Role string `json:"role"`
}
