// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores JWT refresh tokens for user authentication
type RefreshToken struct {
	// Unique refresh token string (hashed)
	Token string `json:"token"`
	// Reference to user who owns this token
	UserID uuid.UUID `json:"user_id"`
	// Token expiration timestamp
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Timestamp when token was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when token was revoked (NULL if active)
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// IP address where token was created (audit trail)
	IpAddress *string `json:"ip_address"`
	// User agent where token was created (audit trail)
	UserAgent *string `json:"user_agent"`
}

// Stores user authentication and profile information
type User struct {
	// Unique user identifier (UUID v4)
	ID uuid.UUID `json:"id"`
	// User email address (unique, used for login)
	Email string `json:"email"`
	// User full name (optional)
	FullName *string `json:"full_name"`
	// Argon2id hashed password
	HashedPassword string `json:"hashed_password"`
	// KYC verification status: pending, verified, or rejected
	KycStatus string `json:"kyc_status"`
	// Timestamp when user was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when user was last updated (auto-updated)
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft delete timestamp (NULL if not deleted)
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
