// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// CountUserActiveTokens returns the number of active sessions for a user.
	CountUserActiveTokens(ctx context.Context, userID uuid.UUID) (int64, error)
	// CountUsers returns the total count of active users.
	CountUsers(ctx context.Context) (int64, error)
	// CreateRefreshToken stores a new refresh token for a user.
	// Includes audit information (IP address and user agent).
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// CreateUser creates a new user with the provided email, full name, and hashed password.
	// Returns the created user record.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// DeleteExpiredTokens removes expired refresh tokens from the database.
	// Should be run periodically as a cleanup job.
	DeleteExpiredTokens(ctx context.Context) error
	// GetRefreshToken retrieves a refresh token by its value.
	// Returns the token regardless of revoked status (caller should check IsRevoked).
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	// GetUserActiveTokens retrieves all active (non-expired, non-revoked) tokens for a user.
	// Useful for session management and "active devices" feature.
	GetUserActiveTokens(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	// GetUserByEmail retrieves a user by their email address.
	// Returns error if user not found or soft-deleted.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// GetUserByID retrieves a user by their unique ID.
	// Returns error if user not found or soft-deleted.
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// ListUsers retrieves paginated list of active users.
	// Supports filtering and pagination.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// RevokeAllUserTokens revokes all active refresh tokens for a user.
	// Used when user logs out from all devices or password changes.
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	// RevokeRefreshToken marks a refresh token as revoked.
	// Sets revoked_at timestamp to current time.
	RevokeRefreshToken(ctx context.Context, token string) (int64, error)
	// SoftDeleteUser marks a user as deleted without removing the record.
	// Sets deleted_at timestamp to current time.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// UpdateUserKYCStatus updates the KYC verification status for a user.
	// Valid statuses: pending, verified, rejected
	UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (User, error)
	// UpdateUserProfile updates user's profile information (full_name).
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
