// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserActiveTokens = `-- name: CountUserActiveTokens :one
SELECT COUNT(*) FROM refresh_tokens
WHERE user_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
`

// CountUserActiveTokens returns the number of active sessions for a user.
func (q *Queries) CountUserActiveTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActiveTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    token,
    user_id,
    expires_at,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING token, user_id, expires_at, created_at, revoked_at, ip_address, user_agent
`

type CreateRefreshTokenParams struct {
	Token     string             `json:"token"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress *string            `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
}

// CreateRefreshToken stores a new refresh token for a user.
// Includes audit information (IP address and user agent).
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
`

// DeleteExpiredTokens removes expired refresh tokens from the database.
// Should be run periodically as a cleanup job.
func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, user_id, expires_at, created_at, revoked_at, ip_address, user_agent FROM refresh_tokens
WHERE token = $1
`

// GetRefreshToken retrieves a refresh token by its value.
// Returns the token regardless of revoked status (caller should check IsRevoked).
func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const getUserActiveTokens = `-- name: GetUserActiveTokens :many
SELECT token, user_id, expires_at, created_at, revoked_at, ip_address, user_agent FROM refresh_tokens
WHERE user_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
ORDER BY created_at DESC
`

// GetUserActiveTokens retrieves all active (non-expired, non-revoked) tokens for a user.
// Useful for session management and "active devices" feature.
func (q *Queries) GetUserActiveTokens(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getUserActiveTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.Token,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

// RevokeAllUserTokens revokes all active refresh tokens for a user.
// Used when user logs out from all devices or password changes.
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token = $1 AND revoked_at IS NULL
`

// RevokeRefreshToken marks a refresh token as revoked.
// Sets revoked_at timestamp to current time.
func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
