// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

// CountUsers returns the total count of active users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    full_name,
    hashed_password,
    kyc_status
) VALUES (
    $1, $2, $3, 'pending'
) RETURNING id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	FullName       *string `json:"full_name"`
	HashedPassword string  `json:"hashed_password"`
}

// CreateUser creates a new user with the provided email, full name, and hashed password.
// Returns the created user record.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.FullName, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

// GetUserByEmail retrieves a user by their email address.
// Returns error if user not found or soft-deleted.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// GetUserByID retrieves a user by their unique ID.
// Returns error if user not found or soft-deleted.
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListUsers retrieves paginated list of active users.
// Supports filtering and pagination.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.HashedPassword,
			&i.KycStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// SoftDeleteUser marks a user as deleted without removing the record.
// Sets deleted_at timestamp to current time.
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserKYCStatus = `-- name: UpdateUserKYCStatus :one
UPDATE users
SET kyc_status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at
`

type UpdateUserKYCStatusParams struct {
	ID        uuid.UUID `json:"id"`
	KycStatus string    `json:"kyc_status"`
}

// UpdateUserKYCStatus updates the KYC verification status for a user.
// Valid statuses: pending, verified, rejected
func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserKYCStatus, arg.ID, arg.KycStatus)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, full_name, hashed_password, kyc_status, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID `json:"id"`
	FullName *string   `json:"full_name"`
}

// UpdateUserProfile updates user's profile information (full_name).
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
